[package]
name = "fixed-map"
version = "0.6.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
categories = ["data-structures"]

description = """
A fixed map where storage layout is calculated by a procedural macro.
"""

documentation = "https://docs.rs/fixed-map"
homepage = "https://github.com/udoprog/fixed-map"
repository = "https://github.com/udoprog/fixed-map"

readme = "README.md"

[dependencies]
fixed-map-derive = {version = "0.6.1", path = "./fixed-map-derive"}
hashbrown = "0.5"

[dev-dependencies]
criterion = { version = "0.2", default-features = false }
hashbrown = "0.5"

[[bench]]
name = "map_benches"
harness = false
